Repository awslabs/palace, pull requests merged in 2023-08, with the labels that each got.

#65 Add singularity container definition file
  .github/workflows/build-and-test-linux-aarch64.yml
  .github/workflows/build-and-test-linux.yml
  .github/workflows/build-and-test-macos.yml
  .github/workflows/docs.yml
  .github/workflows/singularity.yml
  .github/workflows/spack.yml
  .github/workflows/style.yml
  .gitignore
  .gitlab-ci.yml
  CHANGELOG.md
  cmake/ExternalBLASLAPACK.cmake
  docs/src/install.md
  docs/src/run.md
  scripts/format-source
  scripts/palace
  singularity/README.md
  singularity/singularity.def
  test/runtests.jl
  test/testcase.jl
Labels: build, ci

#64 Partial assembly support using libCEED
  CHANGELOG.md
  docs/src/config/solver.md
  palace/drivers/eigensolver.cpp
  palace/fem/multigrid.hpp
  palace/linalg/CMakeLists.txt
  palace/linalg/amg.hpp
  palace/linalg/ams.cpp
  palace/linalg/ams.hpp
  palace/linalg/distrelaxation.cpp
  palace/linalg/distrelaxation.hpp
  palace/linalg/divfree.cpp
  palace/linalg/divfree.hpp
  palace/linalg/gmg.cpp
  palace/linalg/gmg.hpp
  palace/linalg/hcurl.cpp
  palace/linalg/hcurl.hpp
  palace/linalg/ksp.cpp
  palace/linalg/operator.hpp
  palace/linalg/rap.cpp
  palace/main.cpp
  palace/models/curlcurloperator.cpp
  palace/models/curlcurloperator.hpp
  palace/models/domainpostoperator.cpp
  palace/models/domainpostoperator.hpp
  palace/models/laplaceoperator.cpp
  palace/models/laplaceoperator.hpp
  palace/models/postoperator.cpp
  palace/models/romoperator.cpp
  palace/models/romoperator.hpp
  palace/models/spaceoperator.cpp
  palace/models/spaceoperator.hpp
  palace/models/waveportoperator.cpp
  palace/utils/configfile.cpp
  palace/utils/configfile.hpp
  palace/utils/geodata.cpp
  palace/utils/iodata.cpp
  scripts/schema/config/solver.json
Labels: enhancement

#82 Improve enum parsing from JSON
  palace/drivers/transientsolver.cpp
  palace/fem/multigrid.hpp
  palace/linalg/ksp.cpp
  palace/linalg/strumpack.cpp
  palace/main.cpp
  palace/models/lumpedportoperator.cpp
  palace/models/surfacecurrentoperator.cpp
  palace/models/timeoperator.cpp
  palace/utils/configfile.cpp
  palace/utils/configfile.hpp
Labels: minor

#87 Complex-valued operators for multigrid preconditioning
  docs/src/config/solver.md
  palace/drivers/basesolver.cpp
  palace/drivers/basesolver.hpp
  palace/drivers/drivensolver.cpp
  palace/drivers/eigensolver.cpp
  palace/drivers/electrostaticsolver.cpp
  palace/drivers/magnetostaticsolver.cpp
  palace/drivers/transientsolver.cpp
  palace/linalg/chebyshev.cpp
  palace/linalg/chebyshev.hpp
  palace/linalg/distrelaxation.cpp
  palace/linalg/distrelaxation.hpp
  palace/linalg/divfree.cpp
  palace/linalg/gmg.cpp
  palace/linalg/gmg.hpp
  palace/linalg/hcurl.cpp
  palace/linalg/iterative.cpp
  palace/linalg/iterative.hpp
  palace/linalg/jacobi.cpp
  palace/linalg/jacobi.hpp
  palace/linalg/solver.cpp
  palace/linalg/solver.hpp
  palace/models/curlcurloperator.cpp
  palace/models/laplaceoperator.cpp
  palace/models/romoperator.cpp
  palace/models/spaceoperator.cpp
  palace/models/spaceoperator.hpp
  palace/models/timeoperator.cpp
  palace/utils/configfile.cpp
  palace/utils/configfile.hpp
  scripts/schema/config/solver.json
Labels: enhancement

#88 Add option to remove high-order mesh curvature information
  docs/src/config/model.md
  palace/utils/configfile.cpp
  palace/utils/configfile.hpp
  palace/utils/geodata.cpp
  scripts/schema/config/model.json
Labels: enhancement

#93 Updates to fix AMD AOCL CI builds
  .github/workflows/build-and-test-linux.yml
  .gitlab-ci.yml
Labels: ci

#91 Fix Julia exit codes for scripts
  .github/workflows/style.yml
  scripts/format-source
  scripts/schema/config/boundaries.json
  scripts/validate-config
Labels: bug, ci

#95 Fix typos in reference.md
  docs/src/reference.md
Labels: documentation

#94 Fix for non-planar lumped ports
  palace/fem/lumpedelement.hpp
  palace/utils/geodata.cpp
  palace/utils/geodata.hpp
Labels: bug

#69 Improved timing mechanism
  CHANGELOG.md
  docs/src/developer.md
  palace/drivers/basesolver.cpp
  palace/drivers/basesolver.hpp
  palace/drivers/drivensolver.cpp
  palace/drivers/drivensolver.hpp
  palace/drivers/eigensolver.cpp
  palace/drivers/eigensolver.hpp
  palace/drivers/electrostaticsolver.cpp
  palace/drivers/electrostaticsolver.hpp
  palace/drivers/magnetostaticsolver.cpp
  palace/drivers/magnetostaticsolver.hpp
  palace/drivers/transientsolver.cpp
  palace/drivers/transientsolver.hpp
  palace/fem/lumpedelement.hpp
  palace/linalg/gmg.cpp
  palace/linalg/iterative.cpp
  palace/main.cpp
  palace/models/romoperator.cpp
  palace/models/waveportoperator.cpp
  palace/utils/geodata.cpp
  palace/utils/geodata.hpp
  palace/utils/timer.hpp
Labels: enhancement
