Repository awslabs/palace, pull requests merged in 2023-07, with the labels that each got.

#62 Release v0.11.2
  CHANGELOG.md
  CMakeLists.txt
  Makefile
  palace/CMakeLists.txt
  palace/cmake/PkgConfigHelpers.cmake
  scripts/format-source
Labels: release

#67 Make built docs downloadable from CI in PRs
  .github/workflows/docs.yml
Labels: documentation, ci

#72 Fix Documenter cleanup GitHub Action when preview docs are not built
  .github/workflows/docs-cleanup.yml
Labels: ci

#70 Spack recipe updates
  spack/local/packages/palace/package.py
Labels: build

#76 Fix configuration file parsing for obscure `std::regex` bug
  palace/utils/iodata.cpp
  palace/utils/iodata.hpp
Labels: bug
