Repository awslabs/palace, pull requests merged in 2023-03, with the labels that each got.

#20 Fix SuperLUSolver memory bug
  palace/deps/patch/mfem/patch_direct.diff
  palace/linalg/superlu.cpp
  palace/linalg/superlu.hpp
Labels: bug

#21 Refactor constructor helpers
  palace/fem/curlcurloperator.cpp
  palace/fem/curlcurloperator.hpp
  palace/fem/laplaceoperator.cpp
  palace/fem/laplaceoperator.hpp
  palace/fem/spaceoperator.cpp
  palace/fem/spaceoperator.hpp
  palace/utils/multigrid.hpp
Labels: minor

#25 Revise Conductivity variable from int to float
  docs/src/config/boundaries.md
Labels: documentation, minor

#24 Fix bug for second-order absorbing boundary condition
  palace/fem/farfieldboundaryoperator.cpp
  palace/fem/farfieldboundaryoperator.hpp
  palace/fem/spaceoperator.cpp
  palace/fem/spaceoperator.hpp
  palace/utils/mfemcoefficients.hpp
Labels: bug

#26 Bug fix for interface dielectric loss calculations
  examples/cpw/cpw_lumped_adaptive.json
  examples/cpw/cpw_lumped_uniform.json
  examples/cpw/cpw_wave_adaptive.json
  examples/cpw/cpw_wave_uniform.json
  palace/drivers/basesolver.cpp
  palace/linalg/divfree.cpp
  palace/utils/configfile.cpp
  palace/utils/configfile.hpp
  scripts/schema/config/boundaries.json
  test/ref/cpw/lumped_adaptive/domain-Q.csv
  test/ref/cpw/lumped_adaptive/surface-Q.csv
  test/ref/cpw/lumped_uniform/domain-Q.csv
  test/ref/cpw/lumped_uniform/surface-Q.csv
  test/ref/cpw/wave_adaptive/domain-Q.csv
  test/ref/cpw/wave_adaptive/surface-Q.csv
  test/ref/cpw/wave_uniform/domain-Q.csv
  test/ref/cpw/wave_uniform/surface-Q.csv
Labels: bug, minor

#28 Updates to Julia code for `examples/` and `scripts`
  examples/Project.toml
  examples/cavity/cavity.jl
  examples/cavity/convergence_study.jl
  palace/linalg/arpack.cpp
  palace/linalg/slepc.cpp
  scripts/format-source
  scripts/schema/ValidateConfig.jl
  scripts/validate-config
Labels: bug, examples
