Repository awslabs/palace, pull requests merged in 2023-12, with the labels that each got.

#119 Organize the default quadrature rule order
  docs/src/config/solver.md
  docs/src/examples/rings.md
  docs/src/examples/spheres.md
  palace/drivers/drivensolver.cpp
  palace/drivers/eigensolver.cpp
  palace/drivers/electrostaticsolver.cpp
  palace/drivers/magnetostaticsolver.cpp
  palace/drivers/transientsolver.cpp
  palace/fem/bilinearform.cpp
  palace/fem/bilinearform.hpp
  palace/fem/fespace.cpp
  palace/fem/integrator.cpp
  palace/fem/integrator.hpp
  palace/linalg/divfree.cpp
  palace/linalg/divfree.hpp
  palace/linalg/errorestimator.cpp
  palace/linalg/errorestimator.hpp
  palace/linalg/hcurl.cpp
  palace/linalg/hcurl.hpp
  palace/models/curlcurloperator.cpp
  palace/models/curlcurloperator.hpp
  palace/models/domainpostoperator.cpp
  palace/models/laplaceoperator.cpp
  palace/models/laplaceoperator.hpp
  palace/models/romoperator.cpp
  palace/models/spaceoperator.cpp
  palace/models/spaceoperator.hpp
  palace/utils/configfile.cpp
  palace/utils/configfile.hpp
  palace/utils/geodata.cpp
  palace/utils/geodata.hpp
  scripts/schema/config/solver.json
  test/examples/ref/cavity/impedance/error-indicators.csv
  test/examples/ref/cavity/pec/error-indicators.csv
  test/examples/ref/coaxial/matched/error-indicators.csv
  test/examples/ref/coaxial/open/error-indicators.csv
  test/examples/ref/cpw/lumped_adaptive/error-indicators.csv
  test/examples/ref/cpw/lumped_uniform/error-indicators.csv
  test/examples/ref/cpw/wave_adaptive/error-indicators.csv
  test/examples/ref/cpw/wave_uniform/error-indicators.csv
  test/examples/ref/rings/domain-E.csv
  test/examples/ref/rings/error-indicators.csv
  test/examples/ref/rings/probe-B.csv
  test/examples/ref/rings/surface-M.csv
  test/examples/ref/rings/terminal-M.csv
  test/examples/ref/rings/terminal-Minv.csv
  test/examples/ref/rings/terminal-Mm.csv
  test/examples/ref/spheres/domain-E.csv
  test/examples/ref/spheres/error-indicators.csv
  test/examples/ref/spheres/probe-E.csv
  test/examples/ref/spheres/surface-C.csv
  test/examples/ref/spheres/terminal-C.csv
  test/examples/ref/spheres/terminal-Cinv.csv
  test/examples/ref/spheres/terminal-Cm.csv
  test/unit/test-libceed.cpp
Labels: enhancement

#150 Multigrid cleanup from error estimation
  palace/drivers/drivensolver.cpp
  palace/drivers/eigensolver.cpp
  palace/drivers/electrostaticsolver.cpp
  palace/drivers/magnetostaticsolver.cpp
  palace/drivers/transientsolver.cpp
  palace/linalg/errorestimator.cpp
  palace/linalg/errorestimator.hpp
Labels: bug, minor

#153 Return exit code from Palace in wrapper script
  scripts/palace
Labels: bug, minor, usage

#152 Minor formatting and bug fixes
  palace/drivers/basesolver.cpp
  palace/fem/libceed/operator.cpp
  palace/fem/multigrid.hpp
  palace/linalg/gmg.hpp
  palace/linalg/operator.cpp
  palace/linalg/operator.hpp
  scripts/format-source
Labels: bug, minor

#149 Domain energy participation ratio output
  CHANGELOG.md
  palace/drivers/basesolver.cpp
  test/examples/ref/cavity/impedance/domain-E.csv
  test/examples/ref/cavity/pec/domain-E.csv
  test/examples/ref/cpw/lumped_adaptive/domain-E.csv
  test/examples/ref/cpw/lumped_uniform/domain-E.csv
  test/examples/ref/cpw/wave_adaptive/domain-E.csv
  test/examples/ref/cpw/wave_uniform/domain-E.csv
Labels: enhancement, minor

#147 Timer fixes for linear solves
  palace/linalg/divfree.hpp
  palace/linalg/gmg.cpp
  palace/linalg/gmg.hpp
  palace/linalg/iterative.cpp
  palace/linalg/iterative.hpp
  palace/linalg/ksp.cpp
  palace/utils/timer.hpp
Labels: enhancement, minor

#148 Config file option for disabling h-multigrid
  docs/src/config/solver.md
  palace/utils/configfile.cpp
  palace/utils/configfile.hpp
  palace/utils/geodata.cpp
  scripts/schema/config/solver.json
Labels: enhancement, minor, amr

#157 Minor warning fixes
  palace/drivers/basesolver.cpp
  palace/models/timeoperator.cpp
  palace/utils/iodata.cpp
Labels: minor

#158 Fix bug with mesh nondimensionalization for parallel meshes
  palace/models/postoperator.cpp
  palace/models/postoperator.hpp
  palace/utils/geodata.cpp
Labels: bug, postprocessing

#146 Assorted documentation fixes
  CHANGELOG.md
  README.md
  docs/src/config/boundaries.md
  docs/src/config/model.md
  docs/src/config/solver.md
  docs/src/developer.md
  docs/src/examples/cavity.md
  docs/src/examples/coaxial.md
  docs/src/examples/cpw.md
  docs/src/examples/rings.md
  docs/src/examples/spheres.md
  docs/src/guide/boundaries.md
  docs/src/guide/model.md
  docs/src/guide/postprocessing.md
  docs/src/guide/problem.md
  docs/src/index.md
  docs/src/install.md
  docs/src/reference.md
  docs/src/run.md
Labels: documentation, amr

#151 Build system updates
  CMakeLists.txt
  cmake/ExternalGSLIB.cmake
  cmake/ExternalGitTags.cmake
  cmake/ExternalHYPRE.cmake
  cmake/ExternalLibCEED.cmake
  cmake/ExternalMAGMA.cmake
  cmake/ExternalMFEM.cmake
  cmake/ExternalPalace.cmake
  cmake/ExternalSLATE.cmake
  cmake/ExternalSLEPc.cmake
  cmake/ExternalSTRUMPACK.cmake
  cmake/ExternalSuperLU_DIST.cmake
  extern/CMakeLists.txt
  extern/patch/STRUMPACK/patch_gpu_init.diff
  extern/patch/libCEED/patch_gpu_restriction_dev.diff
  extern/patch/libCEED/patch_hcurl_hdiv_basis_cuda_hip.diff
  extern/patch/mfem/patch_cmake_cuda_fix.diff
  extern/patch/mfem/patch_global_variables_threadsafe.diff
  extern/patch/mfem/patch_gslib_leak_fix.diff
  extern/patch/mfem/patch_mesh_const_fix.diff
  extern/patch/mfem/patch_mesh_partitioner_dev.diff
  extern/patch/mfem/patch_mesh_vis_dev.diff
  extern/patch/mfem/patch_ncmesh_interior_boundary_dev.diff
  extern/patch/mfem/patch_par_tet_mesh_fix.diff
  extern/patch/mfem/patch_pfespace_constructor_fix.diff
  extern/patch/mfem/patch_stateless_doftrans_threadsafe.diff
  extern/patch/mfem/patch_strumpack_solver_dev.diff
  extern/patch/petsc/patch_build.diff
  extern/patch/scalapack/patch_version.diff
  palace/CMakeLists.txt
  palace/fem/coefficient.hpp
  singularity/singularity.def
  spack/local/packages/palace/package.py
Labels: build

#159 Release v0.12
  CHANGELOG.md
  CMakeLists.txt
  cmake/ExternalBLASLAPACK.cmake
  cmake/ExternalGitTags.cmake
  cmake/ExternalMFEM.cmake
  extern/patch/mfem/patch_gslib_leak_fix.diff
  extern/patch/mfem/patch_mesh_const_fix.diff
  extern/patch/mfem/patch_mesh_partitioner_dev.diff
  extern/patch/mfem/patch_mesh_vis_dev.diff
  extern/patch/mfem/patch_ncmesh_interior_boundary_dev.diff
  extern/patch/mfem/patch_par_tet_mesh_fix.diff
  palace/CMakeLists.txt
  test/examples/baseline
Labels: release

#160 Fix missing v0.12 changelog updates
  CHANGELOG.md
Labels: documentation, minor
