Repository awslabs/palace, pull requests merged in 2023-10, with the labels that each got.

#85 Introduce Flux Error Estimation
  CHANGELOG.md
  docs/src/config/solver.md
  palace/drivers/basesolver.cpp
  palace/drivers/basesolver.hpp
  palace/drivers/drivensolver.cpp
  palace/drivers/drivensolver.hpp
  palace/drivers/eigensolver.cpp
  palace/drivers/eigensolver.hpp
  palace/drivers/electrostaticsolver.cpp
  palace/drivers/electrostaticsolver.hpp
  palace/drivers/magnetostaticsolver.cpp
  palace/drivers/magnetostaticsolver.hpp
  palace/drivers/transientsolver.cpp
  palace/drivers/transientsolver.hpp
  palace/fem/CMakeLists.txt
  palace/fem/coefficient.hpp
  palace/fem/errorindicator.cpp
  palace/fem/errorindicator.hpp
  palace/fem/integrator.hpp
  palace/linalg/CMakeLists.txt
  palace/linalg/errorestimator.cpp
  palace/linalg/errorestimator.hpp
  palace/main.cpp
  palace/models/curlcurloperator.hpp
  palace/models/laplaceoperator.hpp
  palace/models/materialoperator.cpp
  palace/models/postoperator.cpp
  palace/models/postoperator.hpp
  palace/models/spaceoperator.hpp
  palace/utils/configfile.cpp
  palace/utils/configfile.hpp
  palace/utils/timer.hpp
  scripts/schema/config/solver.json
  test/ref/cavity/impedance/error-indicators.csv
  test/ref/cavity/pec/error-indicators.csv
  test/ref/coaxial/matched/error-indicators.csv
  test/ref/coaxial/open/error-indicators.csv
  test/ref/cpw/lumped_adaptive/error-indicators.csv
  test/ref/cpw/lumped_uniform/error-indicators.csv
  test/ref/cpw/wave_adaptive/error-indicators.csv
  test/ref/cpw/wave_uniform/error-indicators.csv
  test/ref/rings/error-indicators.csv
  test/ref/spheres/error-indicators.csv
  test/runtests.jl
  test/testcase.jl
Labels: enhancement

#104 Fix parsing of 2D COMSOL meshes
  palace/utils/meshio.cpp
Labels: bug, minor

#105 Remove some unneeded `SetIntPoint` calls for `Coefficient` evaluation
  palace/fem/coefficient.hpp
  palace/models/waveportoperator.cpp
Labels: minor, performance

#107 Fix default RPATH for installed targets
  CMakeLists.txt
  cmake/ExternalBLASLAPACK.cmake
  cmake/ExternalMETIS.cmake
  cmake/ExternalSTRUMPACK.cmake
  cmake/ExternalScaLAPACK.cmake
  palace/CMakeLists.txt
  scripts/palace
Labels: build, minor

#108 Disable PETSc signal handling
  palace/linalg/slepc.cpp
Labels: minor

#109 Small fix to MFEM parallel mesh patch
  extern/patch/mfem/patch_par_tet_mesh_fix.diff
Labels: bug

#113 Increase fp precision of first column of postpro files
  palace/drivers/basesolver.cpp
  test/examples/runtests.jl
  test/examples/testcase.jl
Labels: bug, minor

#115 Correct log printing when Palace is built without OpenMP
  palace/main.cpp
Labels: minor

#117 Add library target libpalace.a/.so
  palace/CMakeLists.txt
  palace/cmake/StaticAnalysisHelpers.cmake
  palace/drivers/CMakeLists.txt
  palace/fem/CMakeLists.txt
  palace/linalg/CMakeLists.txt
  palace/models/CMakeLists.txt
  palace/utils/CMakeLists.txt
  test/unit/CMakeLists.txt
Labels: build

#120 Default order for Chebyshev polynomial smoothing
  docs/src/config/solver.md
  palace/linalg/divfree.cpp
  palace/linalg/errorestimator.cpp
  palace/linalg/hcurl.cpp
  palace/utils/configfile.hpp
  palace/utils/iodata.cpp
Labels: enhancement, performance

#118 Refactor construction of discrete interpolator matrices for reuse
  docs/src/config/solver.md
  palace/drivers/basesolver.cpp
  palace/drivers/basesolver.hpp
  palace/drivers/drivensolver.cpp
  palace/drivers/eigensolver.cpp
  palace/drivers/electrostaticsolver.cpp
  palace/drivers/magnetostaticsolver.cpp
  palace/drivers/transientsolver.cpp
  palace/fem/fespace.cpp
  palace/fem/fespace.hpp
  palace/fem/integrator.hpp
  palace/fem/libceed/operator.cpp
  palace/fem/multigrid.hpp
  palace/linalg/ams.cpp
  palace/linalg/ams.hpp
  palace/linalg/distrelaxation.cpp
  palace/linalg/distrelaxation.hpp
  palace/linalg/divfree.cpp
  palace/linalg/divfree.hpp
  palace/linalg/errorestimator.cpp
  palace/linalg/errorestimator.hpp
  palace/linalg/gmg.cpp
  palace/linalg/gmg.hpp
  palace/linalg/hcurl.cpp
  palace/linalg/hcurl.hpp
  palace/linalg/ksp.cpp
  palace/linalg/ksp.hpp
  palace/linalg/operator.hpp
  palace/linalg/rap.cpp
  palace/linalg/rap.hpp
  palace/models/curlcurloperator.cpp
  palace/models/curlcurloperator.hpp
  palace/models/domainpostoperator.cpp
  palace/models/domainpostoperator.hpp
  palace/models/laplaceoperator.cpp
  palace/models/laplaceoperator.hpp
  palace/models/postoperator.cpp
  palace/models/romoperator.cpp
  palace/models/spaceoperator.cpp
  palace/models/spaceoperator.hpp
  palace/models/timeoperator.cpp
  palace/models/timeoperator.hpp
  palace/utils/configfile.cpp
  palace/utils/configfile.hpp
  scripts/schema/config/solver.json
  test/unit/test-libceed.cpp
Labels: enhancement, performance
