Repository awslabs/palace, pull requests merged in 2023-02, with the labels that each got.

#15 Fix GitHub Actions `pkg-config` installation for macOS
  .github/workflows/build-and-test-macos.yml
  .github/workflows/style.yml
Labels: minor

#12 Compiler error fixes for `cppcheck` and `clang-tidy`
  cmake/StaticAnalysisHelpers.cmake
Labels: bug, build

#18 Run GitHub Actions for PRs from forks
  .github/workflows/build-and-test-linux-aarch64.yml
  .github/workflows/build-and-test-linux.yml
  .github/workflows/build-and-test-macos.yml
  .github/workflows/spack.yml
  .github/workflows/style.yml
Labels: build, ci

#16 Fix typos in cavity and convergence examples
  examples/cavity/cavity.jl
  examples/cavity/convergence_study.jl
Labels: documentation, minor

#19 `surface-M.csv` value in docs is incorrect
  docs/src/examples/rings.md
Labels: documentation, minor
