Repository awslabs/palace, pull requests merged in 2023-11, with the labels that each got.

#128 MFEM updates
  cmake/ExternalGitTags.cmake
  cmake/ExternalMFEM.cmake
  docs/src/examples/rings.md
  extern/patch/mfem/patch_cmake_cuda_fix.diff
  extern/patch/mfem/patch_fecoll_vdim_fix.diff
  extern/patch/mfem/patch_global_variables_threadsafe.diff
  extern/patch/mfem/patch_intrules_order_fix.diff
  extern/patch/mfem/patch_kdtree_fix_gcc_13.diff
  extern/patch/mfem/patch_mesh_partitioner_dev.diff
  extern/patch/mfem/patch_mesh_vis_dev.diff
  extern/patch/mfem/patch_mfem_device_fixes.diff
  extern/patch/mfem/patch_ncmesh_interior_boundary_dev.diff
  extern/patch/mfem/patch_par_tet_mesh_fix.diff
  extern/patch/mfem/patch_pfespace_constructor_fix.diff
  extern/patch/mfem/patch_stateless_doftrans_threadsafe.diff
  extern/patch/mfem/patch_strumpack_solver_dev.diff
  palace/fem/coefficient.cpp
  palace/fem/libceed/restriction.cpp
  palace/models/postoperator.cpp
  palace/models/postoperator.hpp
  palace/utils/geodata.cpp
  palace/utils/geodata.hpp
  palace/utils/iodata.cpp
  palace/utils/iodata.hpp
  test/examples/ref/rings/surface-M.csv
Labels: build

#130 libCEED updates
  cmake/ExternalGitTags.cmake
  cmake/ExternalLibCEED.cmake
  extern/patch/libCEED/patch_gpu_restriction_dev.diff
  extern/patch/libCEED/patch_hcurl_hdiv_basis.diff
  extern/patch/libCEED/patch_hcurl_hdiv_basis_cuda_hip.diff
Labels: build

#110 Adaptive Mesh Refinement
  CHANGELOG.md
  README.md
  docs/src/config/boundaries.md
  docs/src/config/model.md
  docs/src/guide/boundaries.md
  docs/src/guide/model.md
  docs/src/index.md
  palace/drivers/basesolver.cpp
  palace/drivers/basesolver.hpp
  palace/drivers/drivensolver.cpp
  palace/drivers/drivensolver.hpp
  palace/drivers/eigensolver.cpp
  palace/drivers/eigensolver.hpp
  palace/drivers/electrostaticsolver.cpp
  palace/drivers/electrostaticsolver.hpp
  palace/drivers/magnetostaticsolver.cpp
  palace/drivers/magnetostaticsolver.hpp
  palace/drivers/transientsolver.cpp
  palace/drivers/transientsolver.hpp
  palace/fem/coefficient.cpp
  palace/fem/errorindicator.cpp
  palace/fem/lumpedelement.cpp
  palace/linalg/vector.hpp
  palace/main.cpp
  palace/utils/CMakeLists.txt
  palace/utils/configfile.cpp
  palace/utils/configfile.hpp
  palace/utils/dorfler.cpp
  palace/utils/dorfler.hpp
  palace/utils/geodata.cpp
  palace/utils/geodata.hpp
  palace/utils/timer.hpp
  scripts/schema/config/model.json
Labels: enhancement

#132 Hotfix for broken ScaLAPACK build
  cmake/ExternalGitTags.cmake
  cmake/ExternalMUMPS.cmake
  cmake/ExternalSTRUMPACK.cmake
  cmake/ExternalScaLAPACK.cmake
  extern/patch/STRUMPACK/patch_gpu_init.diff
  extern/patch/STRUMPACK/patch_parmetis.diff
  extern/patch/mumps/patch_build.diff
  extern/patch/scalapack/patch_build.diff
  extern/patch/scotch/patch_build.diff
  scripts/update-submodules
Labels: bug, build

#133 Add <numeric> header to resolve the MSVC building error
  .clang-format
  palace/fem/coefficient.hpp
  palace/fem/libceed/operator.cpp
  palace/fem/libceed/restriction.cpp
  palace/linalg/arpack.cpp
  palace/utils/diagnostic.hpp
  palace/utils/geodata.cpp
Labels: bug, build, minor

#131 Add bulk magnetic field energy postprocessing
  CHANGELOG.md
  docs/src/config/domains.md
  docs/src/examples/cavity.md
  docs/src/guide/postprocessing.md
  examples/cavity/cavity_impedance.json
  examples/cavity/cavity_pec.json
  examples/cpw/cpw_lumped_adaptive.json
  examples/cpw/cpw_lumped_uniform.json
  examples/cpw/cpw_wave_adaptive.json
  examples/cpw/cpw_wave_uniform.json
  palace/drivers/basesolver.cpp
  palace/models/domainpostoperator.cpp
  palace/models/domainpostoperator.hpp
  palace/models/postoperator.cpp
  palace/models/postoperator.hpp
  palace/models/surfacepostoperator.hpp
  palace/utils/configfile.cpp
  palace/utils/configfile.hpp
  palace/utils/iodata.cpp
  scripts/schema/config/domains.json
  test/examples/ref/cavity/impedance/domain-E.csv
  test/examples/ref/cavity/impedance/domain-Q.csv
  test/examples/ref/cavity/pec/domain-E.csv
  test/examples/ref/cavity/pec/domain-Q.csv
  test/examples/ref/coaxial/matched/domain-E.csv
  test/examples/ref/coaxial/open/domain-E.csv
  test/examples/ref/cpw/lumped_adaptive/domain-E.csv
  test/examples/ref/cpw/lumped_adaptive/domain-Q.csv
  test/examples/ref/cpw/lumped_uniform/domain-E.csv
  test/examples/ref/cpw/lumped_uniform/domain-Q.csv
  test/examples/ref/cpw/wave_adaptive/domain-E.csv
  test/examples/ref/cpw/wave_adaptive/domain-Q.csv
  test/examples/ref/cpw/wave_uniform/domain-E.csv
  test/examples/ref/cpw/wave_uniform/domain-Q.csv
Labels: enhancement, postprocessing

#138 Fix a build issue when MFEM_USE_CUDA or MFEM_USE_HIP enabled
  .github/workflows/build-and-test-linux-aarch64.yml
  .github/workflows/build-and-test-linux.yml
  .github/workflows/build-and-test-macos.yml
  .github/workflows/spack.yml
  palace/main.cpp
Labels: bug, build
