Repository awslabs/palace, pull requests merged in 2024-01, with the labels that each got.

#164 Patch for ParNCMesh::Update bug
  cmake/ExternalMFEM.cmake
  extern/patch/mfem/patch_pncmesh_update_fix.diff
Labels: bug, minor

#154 Cleanup in `geodata.hpp/cpp`
  cmake/ExternalMFEM.cmake
  extern/patch/mfem/patch_pncmesh_update_fix.diff
  palace/drivers/basesolver.cpp
  palace/models/lumpedportoperator.cpp
  palace/models/lumpedportoperator.hpp
  palace/models/surfaceconductivityoperator.cpp
  palace/models/surfaceconductivityoperator.hpp
  palace/models/surfacecurrentoperator.cpp
  palace/models/surfacecurrentoperator.hpp
  palace/models/surfaceimpedanceoperator.cpp
  palace/models/surfaceimpedanceoperator.hpp
  palace/models/waveportoperator.cpp
  palace/models/waveportoperator.hpp
  palace/utils/configfile.cpp
  palace/utils/configfile.hpp
  palace/utils/geodata.cpp
  palace/utils/geodata.hpp
Labels: enhancement

#170 Revert from GitHub METIS/ParMETIS distributions to PETSc forks
  cmake/ExternalGitTags.cmake
  cmake/ExternalHYPRE.cmake
  cmake/ExternalMETIS.cmake
  cmake/ExternalSTRUMPACK.cmake
  extern/patch/GKlib/patch_build.diff
  extern/patch/GKlib/patch_install.diff
  extern/patch/METIS/patch_build.diff
  extern/patch/METIS/patch_idx32.diff
  extern/patch/METIS/patch_idx64.diff
  extern/patch/METIS/patch_install.diff
  extern/patch/METIS/patch_real32.diff
  extern/patch/METIS/patch_real64.diff
  extern/patch/ParMETIS/patch_build.diff
  extern/patch/ParMETIS/patch_install.diff
  extern/patch/ParMETIS/patch_spack.diff
  extern/patch/metis/patch_build.diff
  extern/patch/parmetis/patch_build.diff
Labels: build, ci

#173 Dependency build updates
  CMakeLists.txt
  cmake/ExternalARPACK.cmake
  cmake/ExternalGitTags.cmake
  cmake/ExternalLibCEED.cmake
  cmake/ExternalMETIS.cmake
  cmake/ExternalMFEM.cmake
  cmake/ExternalSTRUMPACK.cmake
  cmake/ExternalScaLAPACK.cmake
  extern/patch/arpack-ng/patch_pzneupd.diff
  extern/patch/libCEED/patch_gpu_restriction_dev.diff
  extern/patch/mfem/patch_getnodalvalues_device_fix.diff
  extern/patch/mfem/patch_mesh_const_fix.diff
  extern/patch/mfem/patch_mesh_partitioner_dev.diff
  extern/patch/mfem/patch_ncmesh_interior_boundary_dev.diff
  extern/patch/mfem/patch_par_tet_mesh_fix.diff
  extern/patch/mfem/patch_pncmesh_update_fix.diff
  extern/patch/scalapack/patch_build.diff
  palace/linalg/arpack.cpp
  scripts/update-submodules
Labels: build

#174 Minor fixes following #166
  palace/main.cpp
  palace/models/lumpedportoperator.cpp
  palace/utils/configfile.hpp
Labels: minor

#167 Revisit multigrid operator construction and full-assembly
  palace/fem/fespace.hpp
  palace/fem/libceed/operator.cpp
  palace/fem/libceed/operator.hpp
  palace/linalg/amg.cpp
  palace/linalg/amg.hpp
  palace/linalg/ams.cpp
  palace/linalg/chebyshev.cpp
  palace/linalg/chebyshev.hpp
  palace/linalg/distrelaxation.cpp
  palace/linalg/distrelaxation.hpp
  palace/linalg/divfree.cpp
  palace/linalg/errorestimator.cpp
  palace/linalg/errorestimator.hpp
  palace/linalg/gmg.cpp
  palace/linalg/gmg.hpp
  palace/linalg/hcurl.cpp
  palace/linalg/jacobi.cpp
  palace/linalg/ksp.cpp
  palace/linalg/mumps.cpp
  palace/linalg/mumps.hpp
  palace/linalg/operator.cpp
  palace/linalg/operator.hpp
  palace/linalg/rap.cpp
  palace/linalg/rap.hpp
  palace/linalg/solver.cpp
  palace/linalg/solver.hpp
  palace/linalg/strumpack.cpp
  palace/linalg/superlu.cpp
  palace/linalg/vector.cpp
  palace/models/curlcurloperator.cpp
  palace/models/laplaceoperator.cpp
  palace/models/romoperator.cpp
  palace/models/spaceoperator.cpp
  palace/models/spaceoperator.hpp
  palace/models/waveportoperator.cpp
Labels: enhancement, performance

#177 Fix regression for electrostatic and magnetostatic postprocessing
  examples/cavity/log.out
  examples/rings/rings.json
  examples/spheres/spheres.json
  palace/drivers/basesolver.cpp
  test/examples/ref/rings/domain-E.csv
  test/examples/ref/spheres/domain-E.csv
Labels: bug, postprocessing
