Repository awslabs/palace, pull requests merged in 2024-06, with the labels that each got.

#259 Add missing commas in config docs
  docs/src/config/boundaries.md
  docs/src/config/problem.md
Labels: documentation

#262 Expose AMS and AMG options in configuration file
  docs/src/config/model.md
  docs/src/config/solver.md
  palace/linalg/amg.cpp
  palace/linalg/amg.hpp
  palace/linalg/ams.cpp
  palace/linalg/ams.hpp
  palace/linalg/divfree.cpp
  palace/linalg/errorestimator.cpp
  palace/utils/configfile.cpp
  palace/utils/configfile.hpp
  palace/utils/iodata.cpp
  scripts/schema/config/solver.json
Labels: documentation, minor

#258 Bug fixes for GPU builds
  CMakeLists.txt
  cmake/ExternalGitTags.cmake
  cmake/ExternalMAGMA.cmake
  cmake/ExternalMETIS.cmake
  cmake/ExternalMFEM.cmake
  cmake/ExternalPalace.cmake
  extern/patch/mfem/patch_nc_internal_bdr_project_fix.diff
Labels: build, GPU

#264 Add conductivity boundaries to Dirichlet BC list for wave ports
  CHANGELOG.md
  docs/src/config/boundaries.md
  docs/src/config/solver.md
  palace/drivers/eigensolver.cpp
  palace/models/waveportoperator.cpp
  palace/models/waveportoperator.hpp
  palace/utils/configfile.cpp
  palace/utils/configfile.hpp
  palace/utils/iodata.cpp
  scripts/schema/config/boundaries.json
Labels: usage, driven

#269 Fix divergence cleaning when a model has no real boundaries
  CHANGELOG.md
  palace/linalg/divfree.cpp
  palace/linalg/divfree.hpp
Labels: bug

#268 Fix oriented bounding box calculation for lumped ports, in preparation for #261
  docs/src/guide/boundaries.md
  palace/fem/lumpedelement.cpp
  palace/utils/geodata.cpp
  palace/utils/geodata.hpp
Labels: bug, mesh
