Repository awslabs/palace, pull requests merged in 2024-05, with the labels that each got.

#239 Update compiler versions for Github Actions
  .github/workflows/build-and-test-linux-aarch64.yml
  .github/workflows/build-and-test-linux.yml
  .github/workflows/build-and-test-macos.yml
Labels: ci

#241 Speed up run-on-arch action
  .github/workflows/build-and-test-linux-aarch64.yml
Labels: ci

#237 Optimize electrostatic and magnetostatic capacitance matrix postprocessing
  palace/drivers/basesolver.cpp
  palace/drivers/electrostaticsolver.cpp
  palace/drivers/electrostaticsolver.hpp
  palace/drivers/magnetostaticsolver.cpp
  palace/drivers/magnetostaticsolver.hpp
  palace/models/domainpostoperator.hpp
  palace/models/postoperator.hpp
  palace/models/surfacepostoperator.hpp
  palace/utils/error.hpp
Labels: enhancement, postprocessing

#246 Fix bounding ball calculation for coaxial lumped ports
  CHANGELOG.md
  palace/fem/lumpedelement.cpp
  palace/fem/lumpedelement.hpp
  palace/utils/geodata.cpp
  palace/utils/geodata.hpp
Labels: bug, mesh

#233 Upgrade error estimation for time-dependent problems
  CHANGELOG.md
  docs/src/reference.md
  palace/drivers/drivensolver.cpp
  palace/drivers/eigensolver.cpp
  palace/drivers/electrostaticsolver.cpp
  palace/drivers/magnetostaticsolver.cpp
  palace/drivers/transientsolver.cpp
  palace/fem/bilinearform.cpp
  palace/fem/bilinearform.hpp
  palace/fem/fespace.cpp
  palace/fem/fespace.hpp
  palace/fem/libceed/integrator.cpp
  palace/fem/multigrid.hpp
  palace/fem/qfunctions/22/hcurlhdiv_error_22_qf.h
  palace/fem/qfunctions/33/hcurlh1d_error_22_qf.h
  palace/fem/qfunctions/33/hcurlh1d_error_33_qf.h
  palace/fem/qfunctions/33/hcurlhdiv_error_33_qf.h
  palace/fem/qfunctions/hcurlh1d_error_qf.h
  palace/fem/qfunctions/hcurlhdiv_error_qf.h
  palace/linalg/CMakeLists.txt
  palace/linalg/ams.cpp
  palace/linalg/ams.hpp
  palace/linalg/densematrix.cpp
  palace/linalg/densematrix.hpp
  palace/linalg/divfree.cpp
  palace/linalg/divfree.hpp
  palace/linalg/errorestimator.cpp
  palace/linalg/errorestimator.hpp
  palace/linalg/hcurl.cpp
  palace/linalg/hcurl.hpp
  palace/linalg/ksp.cpp
  palace/linalg/ksp.hpp
  palace/models/curlcurloperator.cpp
  palace/models/curlcurloperator.hpp
  palace/models/farfieldboundaryoperator.cpp
  palace/models/laplaceoperator.cpp
  palace/models/laplaceoperator.hpp
  palace/models/materialoperator.cpp
  palace/models/spaceoperator.cpp
  palace/models/spaceoperator.hpp
  test/examples/ref/cavity/impedance/error-indicators.csv
  test/examples/ref/cavity/pec/error-indicators.csv
  test/examples/ref/coaxial/matched/error-indicators.csv
  test/examples/ref/coaxial/open/error-indicators.csv
  test/examples/ref/cpw/lumped_adaptive/error-indicators.csv
  test/examples/ref/cpw/lumped_uniform/error-indicators.csv
  test/examples/ref/cpw/wave_adaptive/error-indicators.csv
  test/examples/ref/cpw/wave_uniform/error-indicators.csv
Labels: enhancement, amr

#240 Upgrades for boundary postprocessing
  CHANGELOG.md
  docs/src/config/boundaries.md
  docs/src/config/domains.md
  docs/src/config/model.md
  docs/src/config/solver.md
  docs/src/guide/postprocessing.md
  examples/cpw/cpw_lumped_adaptive.json
  examples/cpw/cpw_lumped_uniform.json
  examples/cpw/cpw_wave_adaptive.json
  examples/cpw/cpw_wave_uniform.json
  examples/rings/rings.json
  examples/spheres/spheres.json
  palace/drivers/basesolver.cpp
  palace/drivers/basesolver.hpp
  palace/drivers/drivensolver.cpp
  palace/drivers/eigensolver.cpp
  palace/drivers/electrostaticsolver.cpp
  palace/drivers/magnetostaticsolver.cpp
  palace/drivers/transientsolver.cpp
  palace/fem/coefficient.cpp
  palace/fem/coefficient.hpp
  palace/fem/gridfunction.hpp
  palace/fem/interpolator.cpp
  palace/models/domainpostoperator.cpp
  palace/models/lumpedportoperator.cpp
  palace/models/postoperator.cpp
  palace/models/postoperator.hpp
  palace/models/surfacepostoperator.cpp
  palace/models/surfacepostoperator.hpp
  palace/models/timeoperator.cpp
  palace/models/timeoperator.hpp
  palace/models/waveportoperator.cpp
  palace/utils/configfile.cpp
  palace/utils/configfile.hpp
  palace/utils/iodata.cpp
  scripts/schema/config/boundaries.json
  scripts/schema/config/domains.json
  scripts/schema/config/model.json
  test/examples/baseline
  test/examples/ref/coaxial/matched/port-I.csv
  test/examples/ref/coaxial/open/port-I.csv
  test/examples/ref/cpw/lumped_adaptive/surface-F.csv
  test/examples/ref/cpw/lumped_uniform/surface-F.csv
  test/examples/ref/cpw/wave_adaptive/surface-F.csv
  test/examples/ref/cpw/wave_uniform/surface-F.csv
  test/examples/ref/rings/surface-F.csv
  test/examples/ref/rings/surface-M.csv
  test/examples/ref/rings/terminal-I.csv
  test/examples/ref/spheres/surface-C.csv
  test/examples/ref/spheres/surface-F.csv
  test/examples/ref/spheres/terminal-V.csv
Labels: enhancement, postprocessing

#242 Snake case consistency
  docs/src/guide/postprocessing.md
  palace/drivers/basesolver.cpp
  palace/drivers/basesolver.hpp
  palace/drivers/drivensolver.cpp
  palace/drivers/drivensolver.hpp
  palace/drivers/eigensolver.cpp
  palace/drivers/eigensolver.hpp
  palace/drivers/electrostaticsolver.cpp
  palace/drivers/electrostaticsolver.hpp
  palace/drivers/magnetostaticsolver.cpp
  palace/drivers/magnetostaticsolver.hpp
  palace/drivers/transientsolver.cpp
  palace/drivers/transientsolver.hpp
  palace/fem/lumpedelement.cpp
  palace/fem/lumpedelement.hpp
  palace/models/farfieldboundaryoperator.cpp
  palace/models/farfieldboundaryoperator.hpp
  palace/models/lumpedportoperator.cpp
  palace/models/lumpedportoperator.hpp
  palace/models/postoperator.cpp
  palace/models/postoperator.hpp
  palace/models/romoperator.cpp
  palace/models/romoperator.hpp
  palace/models/spaceoperator.cpp
  palace/models/spaceoperator.hpp
  palace/models/surfaceimpedanceoperator.cpp
  palace/models/surfaceimpedanceoperator.hpp
  palace/models/timeoperator.cpp
  palace/models/timeoperator.hpp
  palace/utils/configfile.cpp
  palace/utils/configfile.hpp
Labels: minor

#245 Revisiting boundary condition warning messages from #224
  palace/models/curlcurloperator.cpp
  palace/models/farfieldboundaryoperator.cpp
  palace/models/laplaceoperator.cpp
  palace/models/spaceoperator.cpp
  palace/models/surfaceconductivityoperator.cpp
  palace/models/surfaceimpedanceoperator.cpp
  palace/models/surfacepostoperator.cpp
  palace/models/surfacepostoperator.hpp
  palace/utils/communication.hpp
  palace/utils/geodata.cpp
  palace/utils/prettyprint.hpp
Labels: minor

#248 Further improvements to lumped element geometry processing
  docs/src/guide/boundaries.md
  palace/fem/lumpedelement.cpp
  palace/fem/lumpedelement.hpp
  palace/models/curlcurloperator.cpp
  palace/models/lumpedportoperator.cpp
  palace/models/lumpedportoperator.hpp
  palace/models/spaceoperator.cpp
  palace/models/surfacecurrentoperator.cpp
  palace/models/surfacecurrentoperator.hpp
  palace/utils/geodata.cpp
  palace/utils/geodata.hpp
  test/examples/ref/coaxial/matched/domain-E.csv
  test/examples/ref/coaxial/matched/error-indicators.csv
  test/examples/ref/coaxial/matched/port-I.csv
  test/examples/ref/coaxial/matched/port-V.csv
  test/examples/ref/coaxial/open/domain-E.csv
  test/examples/ref/coaxial/open/error-indicators.csv
  test/examples/ref/coaxial/open/port-I.csv
  test/examples/ref/coaxial/open/port-V.csv
Labels: enhancement, mesh

#249 Style fix with updated clang-format for CI
  palace/utils/meshio.cpp
Labels: ci

#236 Add patch for projection onto NC internal boundaries
  CHANGELOG.md
  cmake/ExternalMFEM.cmake
  extern/patch/mfem/patch_nc_internal_project.diff
Labels: bug, amr

#247 Update dependency versions for superbuild
  cmake/ExternalGitTags.cmake
  cmake/ExternalLibCEED.cmake
  cmake/ExternalMFEM.cmake
  cmake/ExternalMUMPS.cmake
  cmake/ExternalSTRUMPACK.cmake
  cmake/ExternalSuperLU_DIST.cmake
  extern/patch/gslib/patch_build.diff
  extern/patch/libCEED/patch_xsmm.diff
  extern/patch/mfem/patch_gmsh_parser_performance.diff
  extern/patch/mfem/patch_hypre_runtime_compute_policy.diff
  extern/patch/mfem/patch_mesh_part_const.diff
  extern/patch/mfem/patch_mesh_partitioner_dev.diff
  extern/patch/mfem/patch_mesh_prism_vtu_fix.diff
  extern/patch/mfem/patch_mesh_vis_dev.diff
  extern/patch/mfem/patch_mfem_device_fixes.diff
  extern/patch/mfem/patch_nc_internal_bdr_project_fix.diff
  extern/patch/mfem/patch_par_tet_mesh_fix_dev.diff
  extern/patch/mfem/patch_workspace_vectors.diff
  extern/patch/mumps/patch_build.diff
  extern/patch/superlu_dist/patch_metis.diff
  extern/patch/superlu_dist/patch_parmetis.diff
  palace/cmake/GetGitDescription.cmake
Labels: ci

#250 Release v0.13
  .github/workflows/build-and-test-linux.yml
  CHANGELOG.md
  CMakeLists.txt
  cmake/ExternalGitTags.cmake
  examples/coaxial/mesh/mesh.jl
  examples/cpw/cpw_coax_adaptive.json
  examples/cpw/cpw_coax_uniform.json
  examples/cpw/mesh/cpw_coax.msh
  examples/cpw/mesh/cpw_coax_0.msh
  examples/cpw/mesh/mesh.jl
  extern/patch/mfem/patch_mesh_part_const.diff
  extern/patch/mfem/patch_nc_internal_bdr_project_fix.diff
  palace/CMakeLists.txt
  palace/models/curlcurloperator.cpp
  palace/models/laplaceoperator.cpp
  palace/models/spaceoperator.cpp
  palace/models/waveportoperator.cpp
Labels: release

#253 Bug fix for boundary postprocessing from #240
  CHANGELOG.md
  palace/fem/coefficient.hpp
Labels: bug, postprocessing

#254 Fix LIBXSMM installation
  .github/workflows/build-and-test-linux.yml
  .github/workflows/build-and-test-macos.yml
  cmake/ExternalLIBXSMM.cmake
Labels: build, ci
