Repository awslabs/palace, pull requests merged in 2025-07, with the labels that each got.

#400 Fix transitive dependency in CUDA builds
  cmake/ExternalGitTags.cmake
  cmake/ExternalMFEM.cmake
  extern/patch/mfem/patch_cuda_hip_compiler_checks.diff
  extern/patch/mfem/patch_gpu_omp.diff
  extern/patch/mfem/patch_mesh_vis_dev.diff
  extern/patch/mfem/patch_missing_host_read_write_fix.diff
  extern/patch/mfem/patch_par_tet_mesh_fix_dev.diff
Labels: GPU

#404 Patch for scalapack to build with gcc-15
  cmake/ExternalGitTags.cmake
Labels: build, minor

#406 Fix bug in bounding box algo for planar boxes.
  palace/fem/lumpedelement.cpp
  palace/utils/geodata.cpp
  test/unit/CMakeLists.txt
  test/unit/test-geodata.cpp
Labels: bug, patch

#413 Fix typos
  .github/workflows/spack.yml
  docs/src/config/domains.md
  docs/src/developer.md
  docs/src/examples/spheres.md
  docs/src/guide/problem.md
  docs/src/install.md
  palace/fem/coefficient.hpp
  palace/models/postoperator.hpp
  test/unit/test-config.cpp
  test/unit/test-libceed.cpp
Labels: documentation, patch
