Repository awslabs/palace, pull requests merged in 2025-08, with the labels that each got.

#432 Skip expensive CI actions when only modifying Markdowns
  .github/workflows/build-and-test-linux.yml
  .github/workflows/build-and-test-macos.yml
  .github/workflows/singularity.yml
  .github/workflows/spack.yml
Labels: minor, ci

#429 Explicit higher order conversion forward map
  cmake/ExternalPalace.cmake
  palace/CMakeLists.txt
  palace/fem/bilinearform.cpp
  palace/fem/interpolator.cpp
  palace/fem/libceed/ceed.cpp
  palace/fem/libceed/ceed.hpp
  palace/fem/mesh.cpp
  palace/linalg/errorestimator.cpp
  palace/utils/geodata.cpp
  palace/utils/geodata.hpp
  test/unit/CMakeLists.txt
  test/unit/test-geodata.cpp
Labels: enhancement, mesh

#433 Normalize the phase of eigenvectors
  CHANGELOG.md
  docs/src/reference.md
  palace/drivers/eigensolver.cpp
  palace/linalg/vector.hpp
Labels: bug, minor, eigenmode

#452 Change CUDA_NVCC_FLAGS to CMAKE_CUDA_FLAGS in magma cmake
  cmake/ExternalMAGMA.cmake
Labels: build, GPU, patch

#456 Fix uninitialized last_normal
  palace/utils/geodata.cpp
Labels: bug, patch

#455 Remove constraint on intel oneAPI in CI
  .github/workflows/build-and-test-linux.yml
Labels: build, ci, patch

#439 Release 0.14.0
  CHANGELOG.md
  CMakeLists.txt
  palace/CMakeLists.txt
Labels: release

#460 Descriptive error message for N=0 in eigenmode
  palace/utils/configfile.cpp
  scripts/schema/config/solver.json
Labels: documentation, minor, eigenmode

#462 Update clang to 18 and gcc to 15 inlight of update macos runners
  .github/workflows/build-and-test-macos.yml
Labels: ci

#415 Add "Quick Start" tutorial
  .github/workflows/docs.yml
  docs/Project.toml
  docs/make.jl
  docs/src/install.md
  docs/src/quick.md
  examples/spheres/mesh/mesh.jl
Labels: documentation

#466 Document TARGET_SOURCES_DEVICE
  docs/src/developer.md
  palace/CMakeLists.txt
Labels: documentation, build
